export interface Atencion{
  id?:string,
  symp:string,
  freqc:number,
  temp:number,
  capilar:number,
  mucosas:string,
  hidra:string,
  resp:number,
  pulse:number,
  state:string,
  appetite:string,
  prono:string,
  treat:string,
  labs:string,
  fechaAtencion:Date,
  estadoat:string,
  vet:string,
  registro:Date,
  entrada: Date,
  salida:Date,
}
