export interface Deceso{
  id?:string,
  estancia:string,
  sector:string,
  registroDeceso:Date,
  responsable:string,
  desc:string,
  antecedentes:string,
  acciones:string,
  informe:string,
  causa:string,
  enfermedad:string,
  factores:string,
  name:string,
  species:string,
  sex:string,
  color:string,
  birthDate:Date,
  breed: string,
  ownerName:string,
  ownerCi:string,
  ownerCellphone:string,
  ownerAddress:string,
}
